version: "2.0"
services:
  prometheus:
    build: ./prometheus
    ports:
      - "9090:9090"
      - "9100:9100"
    networks:
      - frontend
      - backend
    volumes:
      - prometheus-data:/etc/prometheus
    depends_on: 
      - node_exporter
    container_name: prometheus
    extra_hosts:
      - "a1:10.1.3.127"
      - "a2:10.1.3.127"
  grafana:
    build: ./grafana
    ports: 
      - "3000:3000"
    networks:
        - frontend
        - backend
    volumes:
        - grafana_etc:/etc/grafana
        - grafana_usr:/usr/share/grafana 
        - grafana_var:/var/lib/grafana
    container_name: grafana
  node_exporter:
    build: ./node_exporter
    networks:
        - backend
    container_name: node_exporter
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - backend
    volumes:
      - loki-data:/loki

networks:
    frontend:
    backend:

volumes:
    grafana_etc:
    grafana_usr:
    grafana_var:
    loki-data:
    prometheus-data: