name: Deploy to Balena Cloud
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  balena-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Push release to balenaCloud
      uses: balena-io-playground/balena-cloud-github-action@v0.1
      with:
        balena_token: ${{ secrets.BALENA_TOKEN }}
        balena_app_name: 'balena-print-farm-manager'
